networks:
  prod_net:

services:

  redis:
    image: redis:7.0.0-alpine3.15
    ports:
      - "6379:6379"
    networks:
      prod_net:
        aliases:
          - db-redis
  
  mongo:
    image: mongo:4.4.14
    restart: always
    ports:
      - "27017:27017"
    depends_on:
      - redis
    networks:
      prod_net:
        aliases:
          - db-mongo
  
  app:
    image: api_upscale:1.0
    command: python main.py
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - prod_net

  celery:
    image: api_upscale:1.0
    command: sh -c "pip install --upgrade celery redis kombu && celery -A model_tasks.celery worker"
    depends_on:
      - mongo
    networks:
      - prod_net
